"""MCP tools for Abaqus modeling via Python API (abaqus cae noGUI)."""

import json
import time

from ..abaqus_interface.runner import _run_abaqus_cae
from ..abaqus_interface.config import SCRATCH_DIR


async def abaqus_run_modeling(
    script: str,
    save_model: bool = False,
    model_name: str = "model",
    timeout: int = 3600,
) -> str:
    """Execute an Abaqus Python modeling script via `abaqus cae noGUI=`.

    The script has access to the full Abaqus CAE API: mdb, session, abaqusConstants, etc.
    Use standard Abaqus Python API calls to create parts, materials, sections, assemblies,
    steps, loads, boundary conditions, meshes, and jobs.

    Example script:
        from abaqus import *
        from abaqusConstants import *
        import sketch, part, material, section, assembly, step, load, interaction, mesh, job

        model = mdb.Model(name=''beam'')
        # ... modeling commands ...

    Args:
        script: Abaqus Python script content (CAE API).
        save_model: If True, save the model database (.cae) after execution.
        model_name: Base name for saved .cae file.
        timeout: Timeout in seconds.

    Returns:
        JSON string with execution result.
    """
    # Wrap user script with standard imports if they aren''t present
    preamble = """#
# --- Abaqus CAE Python Script (generated by codex-abaqus MCP) ---
from abaqus import *
from abaqusConstants import *
from caeModules import *
import driverUtils

driverUtils.executeOnCaeStartup()

# --- User script below ---
"""
    full_script = preamble + script

    if save_model:
        full_script += f"\n\nmdb.saveAs(pathName='{model_name}.cae')\n"

    result = _run_abaqus_cae(full_script, timeout=timeout)

    return json.dumps({
        "return_code": result.returncode,
        "stdout": result.stdout[-3000:] if result.stdout else "",
        "stderr": result.stderr[-2000:] if result.stderr else "",
        "model_saved": save_model,
        "status": "completed" if result.returncode == 0 else "failed",
    }, default=str)
